# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b88c0146de6de59e9f55123c65ac3c91bfbe9c4bdf01bdfba469138ec1045cceb4401784463b5d44c42485ef11f6c6ce54738a5235d7fe68c7ea41c001e92674

test:
  secret_key_base: 4eb858bab4e891488c6bcfa01a16bc52b0b8c458c18ab8c4b74f31c1fb580c115318212276affc86af2d980177956367a147f1b192814a45e76ae14777581817

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
